### PR TITLE
Ignore true/false/1/0 values for `CACHE_DIR` environment variable

### LINKED ISSUE #26: [regression] find-cache-dir 3.3.0, used through nyc+mocha, causes creation of a folder tree `./false/find-cache-dir/` containing js files
I have a Mocha test suite, code-coveraged by Nyc, run inside Shippable CI with the following command: `NODE_ENV=test nyc --reporter=cobertura --report-dir=../shippable/codecoverage/ mocha --exit --require ./config/mocha.js --recursive test --timeout 80000 --ui bdd -R xunit --reporter-options output=../shippable/testresults/maestro.xml` .

- Using find-cache-dir@3.2.0, tests pass and no folder is created in cwd.
- After re-creating my project's package-lock.json, I got find-cache-dir@3.3.0 (which makes semver sense, since [nyc 15.0.0 depends on `"find-cache-dir": "^3.2.0"`](https://github.com/istanbuljs/nyc/blob/master/package.json#L64)), tests pass, but running the tests now cause creation of a spurious folder named `false`, itself containing a folder named `find-cache-dir`, containing js named `<myOriginalFilename>-<some kind of hash>.js`:

```
false/find-cache-dir/fields-9e2a8b3608c81ff79e5dab523ca0a8c95035eaa14ec95ca88bdc922d0a8e8666.js
false/find-cache-dir/config-a10b75b822f09c2a3fe51c8f4ab42b7a09609eb1a9c065eeb30f475f7049dc2c.js
false/find-cache-dir/index-21c01eca85d0b02b6011525dd4934129ef0384a5aaf6e5a7989eb7c43db9f5e3.js
... [59 other files]
```

- After manually reverting ***only*** find-cache-dir to 3.2.0 in the package-lock (editing the package lock to use the old version & hash), the problem disappears.

I cannot reproduce the issue on my local dev. machine, the issue only arises on Shippable CI. I don't know why yet.

The project uses a package-lock, guaranteeing the only difference is the find-cache-dir version. So, the regression must lie in https://github.com/avajs/find-cache-dir/compare/v3.2.0...v3.3.0 .

Node 12.15.0, Nyc 15.0.0, Mocha 7.1.0. Project is closed source and I cannot share it, sorry. I hope the regression window is enough to find a fix, as I'm unable to reproduce the issue locally and it would be difficult for me to provide a minimal & reliably-reproducible test case.

Thanks.

### PR DESCRIPTION
**Pull request by Richienb**
Fixes #26 

cc @sindresorhus @ronjouch

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -4,6 +4,9 @@ const fs = require('fs');
 const commonDir = require('commondir');
 const pkgDir = require('pkg-dir');
 const makeDir = require('make-dir');
+const yn = require('yn');
```
Comment (sindresorhus) [inline index.js]: `yn` is meant for CLI prompts. Just use the words I mentioned directly.

File: test.js [hunk 2]
```diff
@@ -57,3 +57,9 @@ test('supports CACHE_DIR environment variable', t => {
 
 	delete process.env.CACHE_DIR;
 });
+
+test('ignores yes/no like value for CACHE_DIR environmental variable', t => {
```
Comment (sindresorhus) [inline test.js]:
```suggestion
test('ignores yes/no like value for CACHE_DIR environment variable', t => {
```

File: index.js (hunk 1 above)
Comment (Richienb) [reply index.js]: Fixed!

File: index.js [hunk 3]
```diff
@@ -40,11 +42,11 @@ function getNodeModuleDirectory(directory) {
 }
 
 module.exports = (options = {}) => {
-	if (process.env.CACHE_DIR) {
-		return useDirectory(path.join(process.env.CACHE_DIR, 'find-cache-dir'), options);
+	if (env.CACHE_DIR && !/^true|false|1|0$/.test(env.CACHE_DIR)) {
```
Comment (sindresorhus) [inline index.js]: This regex is incorrect. It will match, for example, `truefalse`. It's also an unnecessary use of regex. Just use an array and Array#includes.

File: readme.md [hunk 4]
```diff
@@ -42,7 +42,7 @@ findCacheDir({name: 'unicorns'});
 
 ### findCacheDir(options?)
 
-Finds the cache directory using the supplied options. The algorithm checks for the `CACHE_DIR` environmental variable, and if one is not found, it tries to find a `package.json` file, searching every parent directory of the `cwd` specified (or implied from other options). It returns a `string` containing the absolute path to the cache directory, or `undefined` if `package.json` was never found or if the `node_modules` directory is unwritable.
+Finds the cache directory using the supplied options. The algorithm checks for the `CACHE_DIR` environmental variable and uses it if it is not set to a yes/no like value. If one is not found, it tries to find a `package.json` file, searching every parent directory of the `cwd` specified (or implied from other options). It returns a `string` containing the absolute path to the cache directory, or `undefined` if `package.json` was never found or if the `node_modules` directory is unwritable.
```
Comment (sindresorhus) [inline readme.md]: This needs to be updated now that `yn` is removed.

File: test.js [hunk 5]
```diff
@@ -57,3 +57,9 @@ test('supports CACHE_DIR environment variable', t => {
 
 	delete process.env.CACHE_DIR;
 });
+
+test('ignores yes/no like value for CACHE_DIR environment variable', t => {
```
Comment (sindresorhus) [inline test.js]: Same as https://github.com/avajs/find-cache-dir/pull/27/files#r389448294

File: index.js (hunk 3 above)
Comment (Richienb) [reply index.js]: Fixed!

File: readme.md (hunk 4 above)
Comment (Richienb) [reply readme.md]: Fixed!

File: test.js (hunk 5 above)
Comment (Richienb) [reply test.js]: Fixed!
